<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Platform\Platform.Abstractions\Platform.Abstractions.csproj" />
    <ProjectReference Include="..\CMDPilot.Risk\CMDPilot.Risk.csproj" />
    <ProjectReference Include="..\CMDPilot.Commands\CMDPilot.Commands.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
